//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockData
    {
        public int Id { get; set; }
        public string sDecimal { get; set; }
        public string sStockIdx { get; set; }
        public string sTypeNo { get; set; }
        public string MarketNo { get; set; }
        public string StockNo { get; set; }
        public string StockName { get; set; }
        public Nullable<int> nAsk { get; set; }
        public Nullable<decimal> fAsk { get; set; }
        public Nullable<int> nBid { get; set; }
        public Nullable<decimal> fBid { get; set; }
        public Nullable<int> nOpen { get; set; }
        public Nullable<decimal> fOpen { get; set; }
        public Nullable<int> nClose { get; set; }
        public Nullable<decimal> fClose { get; set; }
        public Nullable<int> nUp { get; set; }
        public Nullable<decimal> fUp { get; set; }
        public Nullable<int> nDown { get; set; }
        public Nullable<decimal> fDown { get; set; }
        public Nullable<int> nHigh { get; set; }
        public Nullable<decimal> fHigh { get; set; }
        public Nullable<int> nLow { get; set; }
        public Nullable<decimal> fLow { get; set; }
        public Nullable<int> nRef { get; set; }
        public Nullable<decimal> fRef { get; set; }
        public Nullable<int> nFutureOI { get; set; }
        public Nullable<int> nAc { get; set; }
        public Nullable<int> nBc { get; set; }
        public Nullable<int> nTAc { get; set; }
        public Nullable<int> nTBc { get; set; }
        public Nullable<int> nTQty { get; set; }
        public Nullable<int> nTickQty { get; set; }
        public Nullable<int> nYQty { get; set; }
        public Nullable<System.DateTime> DataTime { get; set; }
        public Nullable<int> nSimulate { get; set; }
    }
}
